// alfabet.js
export const WORDS_ALFABET = [
  { ru: "А", no: "A", word: "арбуз", word_no: "ananas", pron: "ar-booz" },
  { ru: "Б", no: "B", word: "банан", word_no: "banan", pron: "ba-nan" },
  { ru: "В", no: "V", word: "вода", word_no: "vann", pron: "va-da" },
  { ru: "Г", no: "G", word: "город", word_no: "by", pron: "go-rad" },
  { ru: "Д", no: "D", word: "дом", word_no: "hus eller hjem", pron: "dom" },
  { ru: "Е", no: "E", word: "еда", word_no: "egg", pron: "ye-da" },
  { ru: "Ё", no: "Jo", word: "ёлка", word_no: "juletre", pron: "yol-ka" },
  { ru: "Ж", no: "Sj", word: "жук", word_no: "bille", pron: "zhook" },
  { ru: "З", no: "Z", word: "зонт", word_no: "paraply", pron: "zont" },
  { ru: "И", no: "I", word: "игра", word_no: "lek", pron: "ee-gra" },
  { ru: "Й", no: "J", word: "йогурт", word_no: "yoghurt", pron: "yo-gurt" },
  { ru: "К", no: "K", word: "кошка", word_no: "katt", pron: "kosh-ka" },
  { ru: "Л", no: "L", word: "лимон", word_no: "lime", pron: "lee-mon" },
  { ru: "М", no: "M", word: "молоко", word_no: "melk", pron: "ma-la-ko" },
  { ru: "Н", no: "N", word: "нос", word_no: "nese", pron: "nos" },
  { ru: "О", no: "O", word: "окно", word_no: "oppslag", pron: "ak-no" },
  { ru: "П", no: "P", word: "папа", word_no: "pappa", pron: "pa-pa" },
  { ru: "Р", no: "R", word: "река", word_no: "elv", pron: "re-ka" },
  { ru: "С", no: "S", word: "собака", word_no: "hund", pron: "sa-ba-ka" },
  { ru: "Т", no: "T", word: "торт", word_no: "kake", pron: "tort" },
  { ru: "У", no: "U", word: "улица", word_no: "gate", pron: "u-li-tsa" },
  { ru: "Ф", no: "F", word: "фрукт", word_no: "frukt", pron: "frukt" },
  { ru: "Х", no: "Kh", word: "хлеб", word_no: "brød", pron: "khlyeb" },
  { ru: "Ц", no: "Ts", word: "цветок", word_no: "blomst", pron: "tsve-tok" },
  { ru: "Ч", no: "Tj", word: "чай", word_no: "te", pron: "chai" },
  { ru: "Ш", no: "Sj", word: "школа", word_no: "skole", pron: "shko-la" },
  { ru: "Щ", no: "Sjtj", word: "щука", word_no: "gjedde", pron: "shchu-ka" },
  { ru: "Ъ", no: "(hard tegn)", word: "(ingen ord)", word_no: "" },
  { ru: "Ы", no: "Y", word: "сыр", word_no: "ost", pron: "sir" },
  { ru: "Ь", no: "(myk tegn)", word: "(ingen ord)", word_no: "" },
  { ru: "Э", no: "E", word: "экран", word_no: "skjerm", pron: "ek-ran" },
  { ru: "Ю", no: "Ju", word: "юла", word_no: "snurrebass", pron: "yu-la" },
  { ru: "Я", no: "Ja", word: "яблоко", word_no: "eple", pron: "ya-bla-ka" }
];
